INVALID=-1
HOMEID_SZ=4
SRC_ID_SZ=1
DST_ID_SZ=1
P1_SZ=1
P2_SZ=1
P3_SZ=1
HOPS_REPEATER_COUNT_SZ=1

DATA_LENGTH_SZ=1

"""protocol globals"""
ZNIFFER_4X_DATA_FRAME_SOF = 0x21
ZNIFFER_4X_COMMAND_FRAME_SOF = 0x23
ZNIFFER_4X_DATA_FRAME_CHANNEL_SHIFT = 0x05
ZNIFFER_4X_DATA_FRAME_SPEED_MASK = 0x1F
ZNIFFER_4X_IS_WAKEUP_DATA_MARKER = 0x02
ZNIFFER_4X_IS_SOF_MARKER = 0x01
ZNIFFER_4X_IS_DATA_MARKER = 0x03
ZNIFFER_4X_IS_SOF_WAKEUP_START_MARKER = 0x04
ZNIFFER_4X_IS_SOF_WAKEUP_STOP_MARKER = 0x05


ZNIFFER_4X_COMMAND_SET_BAUD_RATE=0x0E
ZNIFFER_4X_COMMAND_GET_FREQUENCIES=0x03
ZNIFFER_4X_COMMAND_GET_FREQUENCIES_STR=0x13
ZNIFFER_4X_COMMAND_TYPE_START=0x04
ZNIFFER_4X_COMMAND_TYPE_STOP=0x05
ZNIFFER_4X_COMMAND_TYPE_SET_FREQUENCY=0x02
ZNIFFER_4X_COMMAND_TYPE_GET_VERSION=0x01

#warning, we're currently only supporting BaseHeader=0 for the moment.
COMMAND_FREQUENCY_CODE_EU=0#  BaseHeader="0" Text="868.4 MHz (EU)"
COMMAND_FREQUENCY_CODE_US=1#  BaseHeader="0" Text="908.4 MHz (US)"
COMMAND_FREQUENCY_CODE_ANZ=2#  BaseHeader="0" Text="921.4 MHz (ANZ)"
COMMAND_FREQUENCY_CODE_HK=3#  BaseHeader="0" Text="919.8 MHz (HK)"
COMMAND_FREQUENCY_CODE_TF1_EU=4#  BaseHeader="0" Text="866.42 MHz (TF1 EU)"
COMMAND_FREQUENCY_CODE_TF2_EU=5#  BaseHeader="0" Text="870.42 MHz (TF2 EU)"
COMMAND_FREQUENCY_CODE_TF3_US=6#  BaseHeader="0" Text="906.42 MHz (TF3 US)"
COMMAND_FREQUENCY_CODE_TF4_US=7#  BaseHeader="0" Text="910.42 MHz (TF4 US)"
COMMAND_FREQUENCY_CODE_MY=8#  BaseHeader="0" Text="868.2 MHz (MY)"
COMMAND_FREQUENCY_CODE_IN=9#  BaseHeader="0" Text="865.22 MHz (IN)"
COMMAND_FREQUENCY_CODE_TF5=11#  BaseHeader="0" Text="878 MHz (TF5)"
COMMAND_FREQUENCY_CODE_TF6=12#  BaseHeader="0" Text="882 MHz (TF6)"
COMMAND_FREQUENCY_CODE_TF7=13#  BaseHeader="0" Text="886 MHz (TF7)"
COMMAND_FREQUENCY_CODE_RU=26#  BaseHeader="0" Text="869.0 MHz (RU)"
COMMAND_FREQUENCY_CODE_IL=27#  BaseHeader="0" Text="916 MHz (IL)"

COMMAND_FREQUENCY_CODE_JP=10#  BaseHeader="1" Text="926.3 MHz (JP)"
COMMAND_FREQUENCY_CODE_TF8_3CH=14#  BaseHeader="1" Text="932 MHz (TF8 3CH)"
COMMAND_FREQUENCY_CODE_TF9_3CH=15#  BaseHeader="1" Text="940 MHz (TF9 3CH)"
COMMAND_FREQUENCY_CODE_TF10_3CH=16#  BaseHeader="1" Text="840 MHz (TF10 3CH)"
COMMAND_FREQUENCY_CODE_TF11_3CH=17#  BaseHeader="1" Text="850 MHz (TF11 3CH)"
COMMAND_FREQUENCY_CODE_JP_32MHz=18#  BaseHeader="1" Text="951.1 MHz (JP 32MHz)"
COMMAND_FREQUENCY_CODE_JP_OLD=19#  BaseHeader="1" Text="950.95 MHz (JP)"
COMMAND_FREQUENCY_CODE_KR=28#  BaseHeader="1" Text="919.7 MHz (KR)"


HEADER_TYPE_SINGLECAST=0x01
HEADER_TYPE_ACK=0x03
HEADER_TYPE_EXPLORER=0x05

COMMAND_BAUD_RATE_115200=0x00
COMMAND_BAUD_RATE_230400=0x01


COMMAND_PAYLOAD_ZERO=0x00

ZnifferCommandTypesEnum = []
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_SET_BAUD_RATE)
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_GET_FREQUENCIES)
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_GET_FREQUENCIES_STR)
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_TYPE_START)
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_TYPE_STOP)
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_TYPE_SET_FREQUENCY)
ZnifferCommandTypesEnum.append(ZNIFFER_4X_COMMAND_TYPE_GET_VERSION)
