ASSIGN_COMPLETE          =  0x00
ASSIGN_NODEID_DONE       = 0x01
ASSIGN_RANGE_INFO_UPDATE  = 0x02
ZW_SET_LEARN_MODE_DISABLE            = 0x00
ZW_SET_LEARN_MODE_CLASSIC           = 0x01
ZW_SET_LEARN_MODE_NWI               = 0x02