#!/bin/sh

while [ "$var1" != "end" ]
do
pingtime=$(ping -w 1 8.8.8.8 | grep ttl)
if [ "$pingtime" = "" ]
then
   pingtimetwo=$(ping -w 1 74.125.91.105 | grep ttl)
   if [ "$pingtimetwo" = "" ]
   then
       clear ; echo 'down'
   else
       clear ; echo 'up'
   fi
else
    clear ; echo 'up'
fi
exit 1

done
