#!/bin/sh
echo ledblink 3 1 1 > /proc/sercomm_gpio
echo "start"

FILE="/www/zniffer/data/actual_script.txt"
OUT=$(awk '{ print $1 }' $FILE)
echo $OUT
ZNIF="zniffer"
SPEC="spectrum"

echo "" > /www/zniffer/data/zniffer.csv

if [ $OUT == $ZNIF ];
  then
    rwee -d
    rwee -n
    python /www/zniffer/zniffer.py --output_csv --region US -i /dev/ttyS0 -o /www/zniffer/data/zniffer.zlf
else
  if [ $OUT == $SPEC ];
    then
      rwee -w -z -x -f /www/data/firmware/zniffer
      echo "zniffer" > /www/zniffer/data/actual_script.txt
      rwee -d
      rwee -n
      python /www/zniffer/zniffer.py --output_csv --region US -i /dev/ttyS0 -o /www/zniffer/data/zniffer.zlf
  fi
fi
