#!/bin/bash

echo "start"
python /home/magni/public_html/analyzer/zniffer/zniffer.py --output_csv --region US -i /dev/ttyACM0 -o /home/magni/public_html/analyzer/zniffer/data/zniffer.zlf

echo "start"
