#!/bin/sh
echo ledblink 3 2 2 > /proc/sercomm_gpio

FILE="/www/zniffer/data/actual_script.txt"
OUT=$(awk '{ print $1 }' $FILE)
echo $OUT
ZNIF="zniffer"
SPEC="spectrum"

if [ $OUT != $SPEC ];
  then
    rwee -w -z -x -f /www/data/firmware/spectrum
    echo "spectrum" > /www/zniffer/data/actual_script.txt
    rwee -d
    rwee -n
    python /www/zniffer/analyzer.py
else
  if [ $OUT == $SPEC ];
    then
      rwee -d
      rwee -n
      sleep 1
      python /www/zniffer/analyzer.py
  fi
fi
